// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL4AyRxDny4lf_IIidGWXs71nI4EK8Dlw',
    appId: '1:686130032431:web:665aa1f0b354560d0dbbda',
    messagingSenderId: '686130032431',
    projectId: 'chat-app-398fc',
    authDomain: 'chat-app-398fc.firebaseapp.com',
    storageBucket: 'chat-app-398fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClfQFCNf4HOxX6nFQqHpdYZAFje-csTSs',
    appId: '1:686130032431:android:f04518527978dfb60dbbda',
    messagingSenderId: '686130032431',
    projectId: 'chat-app-398fc',
    storageBucket: 'chat-app-398fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA4_RraPFVCDCYaGCP69OjI2N0Qc_zFK4',
    appId: '1:686130032431:ios:8ae7d4d76f18a8df0dbbda',
    messagingSenderId: '686130032431',
    projectId: 'chat-app-398fc',
    storageBucket: 'chat-app-398fc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA4_RraPFVCDCYaGCP69OjI2N0Qc_zFK4',
    appId: '1:686130032431:ios:8ae7d4d76f18a8df0dbbda',
    messagingSenderId: '686130032431',
    projectId: 'chat-app-398fc',
    storageBucket: 'chat-app-398fc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL4AyRxDny4lf_IIidGWXs71nI4EK8Dlw',
    appId: '1:686130032431:web:689b5e29e3d0a0160dbbda',
    messagingSenderId: '686130032431',
    projectId: 'chat-app-398fc',
    authDomain: 'chat-app-398fc.firebaseapp.com',
    storageBucket: 'chat-app-398fc.appspot.com',
  );
}
